### ISSUE TITLE
Clicking on a sprite while using a when clicked hat causes skip to crash

### ISSUE THREAD

**Issue by hyperobject** [tjvr/skip#1]
Something to do with Scratch's coordinate system vs. PyGame's?

Traceback (most recent call last):
  File "pygame_screen.py", line 307, in <module>
    main(project)
  File "pygame_screen.py", line 229, in main
    screen.tick()
  File "pygame_screen.py", line 102, in tick
    for event in self.interpreter.tick(events):
  File "/home/tiberiusgeek/skip/skip/**init**.py", line 148, in tick
    if self.screen.touching_mouse(sprite):
  File "pygame_screen.py", line 170, in touching_mouse
    return bool(mask.get_at((int(mx - x), int(my - y))))
IndexError: 25, 7 is out of bounds

**Comment by tjvr** [comment]
Thank you for reporting this! I'd been struggling with it but hadn't
clarified why. I'd forgotten to rotate/scale the mask. Thanks!

**Comment by tjvr** [comment]
Hmm. Doesn't appear to be anyway to rotate a mask in Pygame...
