### ISSUE TITLE
If on edge, bounce blocks crash skip

### ISSUE THREAD

**Issue by hyperobject** [tjvr/skip#2]
Traceback (most recent call last):
  File "pygame_screen.py", line 307, in <module>
    main(project)
  File "pygame_screen.py", line 229, in main
    screen.tick()
  File "pygame_screen.py", line 102, in tick
    for event in self.interpreter.tick(events):
  File "/home/tiberiusgeek/skip/skip/**init**.py", line 174, in tick
    for event in thread.tick():
  File "/home/tiberiusgeek/skip/skip/**init**.py", line 39, in tick
    event = self.generator.next()
  File "/home/tiberiusgeek/skip/skip/**init**.py", line 208, in run_script
    for x in self.evaluate(s, block):
  File "/home/tiberiusgeek/skip/skip/**init**.py", line 246, in flatten_generators
    for x in flatten_generators(item):
  File "/home/tiberiusgeek/skip/skip/**init**.py", line 244, in flatten_generators
    for item in gen:
  File "/home/tiberiusgeek/skip/skip/**init**.py", line 208, in run_script
    for x in self.evaluate(s, block):
  File "/home/tiberiusgeek/skip/skip/**init**.py", line 230, in evaluate
    value = value.type._workaround(value)
TypeError: 'NoneType' object is not callable

**Comment by tjvr** [comment]
Good catch. It's probably supposed to raise kurt.UnsupportedBlock or
something.

**Comment by tjvr** [comment]
Okay, now it raises the correct error for blocks that aren't implemented yet.

Could you implement the "if on edge, bounce" block? :)

**Comment by hyperobject** [comment]
Possibly. Give me a few days. ;)

**Comment by tjvr** [comment]
> Possibly. Give me a few days. ;)

_bump_... ;)

**Comment by hyperobject** [comment]
Possibly. Give me a decade. :P
